---
title: "Apartamentos a la venta en Mercado Libre"
subtitle: "Análisis exploratorio de datos"
author: ""
date: ""
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, comment = FALSE, cache = TRUE)
library(readr)
library(here)
library(data.table)
library(tidyverse)
library(knitr)
library(lubridate)
library(magrittr)
library(ggcorrplot)
library(corrplot)
library(RColorBrewer)
library(ggcorrplot)
```



```{r datos}
aptos_yearmonth <- list.files(path = here("mercado_libre/API/datos/limpios/apt"), pattern = "*.csv", full.names = T)

yearmonth <- c('aptos_202106','aptos_202107')

aptos <- sapply(aptos_yearmonth, FUN=function(yearmonth){
      read_csv(file=yearmonth)}, simplify=FALSE) %>% bind_rows()

aptos <- aptos %>% group_by(id) %>% 
  arrange(desc(fecha_bajada)) %>%
  slice(1) %>% ungroup()

aptos <- aptos %>% mutate_if(is.character, as.factor)

```


El total de observaciones en la base de datos es de `r paste(dim(aptos)[1])`, mientras que el total de variables es de `r paste(dim(aptos)[2])`.

El total de observaciones sin `NA` es de `r paste(dim(aptos %>% drop_na())[1])`.

Las proporciones de NA por variable son:


```{r, results='asis'}
p_na <- sapply(aptos, function(x) round(sum(is.na(x))/length(x),3)) %>% data.frame() %>% 
   rename(prop_na=".") %>% arrange(desc(prop_na))

p_na %>%  filter(p_na > 0) %>% kable(booktabs=T)
```


El total de observaciones sin `NA` luego de quitar las variables con proprcion de `NA` superior a 10 % es de `r paste(dim(aptos %>% drop_na())[1])`.

```{r,  fig.cap='Histograma del precio de oferta de los apartamentos a la venta en Montevideo (en logaritmos)'}
aptos %>% ggplot(aes(x=log(price))) + 
       geom_histogram(fill = 'darkgreen', alpha = 1, bins = 40) +
      theme(axis.ticks.x = element_blank(),
            legend.position = 'none',
            axis.title.y = element_blank(),
            axis.title.x = element_text(face = 'bold', size = 12),
            axis.text.x = element_text(face = 'bold')) +
      xlim(9,16) +
      labs(x = 'Precio de oferta (en logaritmos)') +
      scale_fill_manual(values = c('darkgreen')) 
```


```{r, results = 'asis'}

aptos$ingresomedio_ech %>% 
      fct_relevel('Alto', 'Medio - Alto', 'Medio - Bajo', 'Bajo') %>% 
      table() %>% kable()

```

```{r, fig.cap='Gráfico de violin del precio de publicación (en logaritmos) según zona respecto a avenida italia'}
aptos %>% 
      ggplot(aes(x=as.character(zona_avditalia), y=log(price),
                 fill=as.character(zona_avditalia))) + 
      geom_violin() +
      theme(text = element_text( family = 'sans'),
            axis.title.y = element_text( size = 14),
            axis.title.x = element_blank(),
            plot.title = element_blank(),
            legend.title = element_blank(),
            axis.text.x = element_text(face = 'bold', size = 12),
            axis.text.y = element_text(face = 'bold', size = 12),
            legend.position = 'none') +
      scale_x_discrete() +
      ylab('Logaritmo del precio de publicación') +
      geom_boxplot(width=0.1, colour='black', outlier.color = 'black') 
```

```{r, fig.cap='Gráfico de violin del precio de publicación (en logaritmos) según dist_shop'}

aptos %>% 
      ggplot(aes(x=as.character(dist_shop), y=log(price),
                 fill=as.character(dist_shop))) + 
      geom_violin() +
      theme(text = element_text( family = 'sans'),
            axis.title.y = element_text( size = 14),
            axis.title.x = element_blank(),
            plot.title = element_blank(),
            legend.title = element_blank(),
            axis.text.x = element_text(face = 'bold', size = 12),
            axis.text.y = element_text(face = 'bold', size = 12),
            legend.position = 'none') +
      scale_x_discrete() +
      ylab('Logaritmo del precio de publicación') +
      geom_boxplot(width=0.1, colour='black', outlier.color = 'black') +
      facet_wrap(~ingresomedio_ech)
```


```{r, fig.cap='Gráfico de dispersión del precio de publicación (en logaritmos) según distancia a la rambla por nivel de ingreso'}

aptos %>% 
      ggplot(aes(x=dist_rambla, y=log(price), alpha = 1/3)) + 
      geom_point(color = 'navyblue') +
      theme(text = element_text( family = 'sans'),
            axis.title.y = element_text( size = 14),
            axis.title.x = element_blank(),
            plot.title = element_blank(),
            legend.title = element_blank(),
            axis.text.x = element_text(face = 'bold', size = 12),
            axis.text.y = element_text(face = 'bold', size = 12),
            legend.position = 'none') +
      scale_x_discrete() +
      ylab('Logaritmo del precio de publicación') +
      xlab('Distancia a la rambla (en m2)') +
      facet_wrap(~full_bathrooms)

```

```{r, fig.cap='Gráfico de Violin del precio de publicación (en logaritmos) según el apartamento tenga un solo baño (o ninguno) completo o más de uno'}

aptos %>%
      filter(!is.na(full_bathrooms)) %>%
      ggplot(aes(x=as.character(full_bathrooms), y=log(price), 
                 fill=as.character(full_bathrooms))) + 
      geom_violin() +
      theme(text = element_text( family = 'sans'),
            axis.title.y = element_text( size = 14),
            axis.title.x = element_blank(),
            plot.title = element_blank(),
            legend.title = element_blank(),
            axis.text.x = element_text(face = 'bold', size = 12),
            axis.text.y = element_text(face = 'bold', size = 12),
            legend.position = 'none') +
      scale_x_discrete() +
      ylab('Precio de publicación (en logaritmos)') +
      geom_boxplot(width=0.1, colour='black', outlier.color = 'black')

```


```{r, fig.cap='Gráfico de Violin del precio de publicación (en logaritmos) según distancia al shopping más cercano'}

aptos %>%
      ggplot(aes(x=as.character(dist_shop), y = log(price), 
                 fill=as.character(dist_shop))) + 
      geom_violin() +
      theme(text = element_text( family = 'sans'),
            axis.title.y = element_text( size = 14),
            axis.title.x = element_blank(),
            plot.title = element_blank(),
            legend.title = element_blank(),
            axis.text.x = element_text(face = 'bold', size = 12),
            axis.text.y = element_text(face = 'bold', size = 12),
            legend.position = 'none') +
      scale_x_discrete() +
      ylab('Precio de publicación') +
      geom_boxplot(width=0.1, colour='black', outlier.color = 'black')

```


```{r, fig.cap='Gráfico de violin del precio de publicación (en logaritmos) según distancia a un shopping y zona respecto a avenida italia'}

aptos %>% 
      ggplot(aes(x=as.character(dist_shop), y=log(price), 
                 fill=as.character(dist_shop))) + 
      geom_violin() +
      theme(text = element_text( family = 'sans'),
            axis.title.y = element_text( size = 14),
            axis.title.x = element_blank(),
            plot.title = element_blank(),
            legend.title = element_blank(),
            axis.text.x = element_text(face = 'bold', size = 12),
            axis.text.y = element_text(face = 'bold', size = 12),
            legend.position = 'none') +
      scale_x_discrete() +
      ylab('Precio de publicación (en logaritmos)') +
      geom_boxplot(width=0.1, colour='black', outlier.color = 'black') +
      facet_wrap(~zona_avditalia)

```


```{r, fig.cap='Boxplot del precio de publicación según zona respecto a avenida itala y bedrooms'}

aptos %>%
      ggplot(aes(x=zona_avditalia, y=log(price), 
                 fill=as.character(zona_avditalia))) +  
      theme(text = element_text( family = 'sans'),
            axis.title.y = element_text( size = 14),
            axis.title.x = element_blank(),
            plot.title = element_blank(),
            legend.title = element_blank(),
            axis.text.x = element_text(face = 'bold', size = 12),
            axis.text.y = element_text(face = 'bold', size = 12),
            legend.position = 'none') +
      scale_x_discrete() +
      ylab('Precio de publicación') +
      geom_boxplot(width=0.1, colour='black', outlier.color = 'black') +
      facet_wrap(~has_security)

```



```{r, fig.cap = 'Gráfico de barras de la cantidad de baños completos'}
aptos %>% ggplot() +
      geom_bar(aes(x = fct_infreq(as.factor(full_bathrooms)), y = (..count..)/sum(..count..), fill = full_bathrooms)) +
      theme(axis.ticks.x = element_blank(),
            legend.position = 'none',
            axis.title.y = element_blank(),
            axis.title.x = element_text(face = 'bold', size = 12),
            axis.text.x = element_text(face = 'bold')) + 
      scale_y_continuous(labels = scales::percent) +
      geom_text(aes(x = as.factor(full_bathrooms),label = scales::percent(round((..count..)/sum(..count..), 2)), 
                    y = (..count..)/sum(..count..)), stat = "count", vjust = -0.5, size = 3) + 
      labs(x = 'Cantidad de baños completos')

```


```{r, fig.cap = 'Gráfico de barras de la cantidad de dormitorios'}
aptos %>% ggplot() +
      geom_bar(aes(x = bedrooms, y = (..count..)/sum(..count..), fill = bedrooms)) +
      theme(axis.ticks.x = element_blank(),
            legend.position = 'none',
            axis.title.y = element_blank(),
            axis.title.x = element_text(face = 'bold', size = 12),
            axis.text.x = element_text(face = 'bold')) + 
      scale_y_continuous(labels = scales::percent) +
      geom_text(aes(x = as.factor(bedrooms),label = scales::percent(round((..count..)/sum(..count..), 2)), 
                    y = (..count..)/sum(..count..)), stat = "count", vjust = -0.5, size = 2) + 
      labs(x = 'Cantidad de dormitorios')
```


```{r, fig.cap='Gráfico de puntos del precio de publicación en logaritmos y distancia a la rambla por cantidad de habitaciones'}

aptos %>%
      ggplot(aes(x=dist_rambla, y = log(price))) + 
      geom_point(color = 'firebrick') +
      theme(text = element_text( family = 'sans'),
            axis.title.y = element_text( size = 14),
            axis.title.x = element_blank(),
            plot.title = element_blank(),
            legend.title = element_blank(),
            axis.text.x = element_text(face = 'bold', size = 12),
            axis.text.y = element_text(face = 'bold', size = 12),
            legend.position = 'none') +
      scale_x_discrete() +
      xlab('Distancia a la rambla (m2)') +
      ylab('Precio de publicación') +
      facet_wrap(~bedrooms)

```



```{r}
aptos_cor <- aptos %>% select(price, maintenance_fee, dist_rambla, covered_area,
                              total_area, no_covered_area) %>% mutate(logprice = log(price))

corr<-round(cor(aptos_cor[,-1], use='pairwise.complete.obs') , 2)

ggcorrplot(corr, method = c("square"),type=c("upper"), 
           ggtheme = ggplot2::theme_gray,lab=TRUE)

```



























