---
title: "Análisis exploratorio de datos - Aptos ML"
author: "Alvaro Valiño - Lucia Coudet"
date: "2 de mayo de 2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, comment = FALSE, cache = FALSE)
library(readr)
library(here)
library(data.table)
library(tidyverse)
library(knitr)
library(lubridate)
library(magrittr)
```



```{r datos}
barrios_aptos <- list.files(path = here("mercado_libre/API/datos/apt/202105"), pattern = "*.csv", full.names = T)
barrios_casas <- list.files(path = here("mercado_libre/API/datos/casas/202105"), pattern = "*.csv", full.names = T)

aptos_total <- sapply(barrios_aptos, FUN=function(id_barrio){
      read_csv(file=id_barrio,col_types = cols(.default = "c"))}, simplify=FALSE) %>% bind_rows()

casas_total <- sapply(barrios_casas, FUN=function(id_barrio){
      read_csv(file=id_barrio,col_types = cols(.default = "c"))}, simplify=FALSE) %>% bind_rows()

```


```{r}
aptos_total <- aptos_total %>%  
      separate(col = 'covered_area', into = c("covered_area", "covered_area_unidad"), sep = "\\s") %>% 
      separate(col = 'total_area', into = c('total_area', 'total_area_unidad'), sep = "\\s") %>%
      mutate(covered_area =  as.numeric(covered_area),
             total_area = as.numeric(total_area),
             price = as.numeric(price),
             latitude = as.numeric(latitude),
             longitude = as.numeric(longitude),
             dia = as_date(dia),
             date_created = as_date(date_created),
             last_updated = as_date(last_updated))
```


```{r limpiado}
cuantil <- aptos_total %>% filter(price < 40000) %>% select(price) %$% quantile(.$price, 0.25)

aptos <- aptos_total %>% filter(price != 11111111, price != 111111111, price > cuantil)
```

El total de observaciones sin `NA` es de:

```{r NAs}
dim(aptos %>% select(-'mlu1472-mtrs',-'mlu1472-mtrstotal', -'seller_contact', -'has_air_conditioning',
                 - 'has_telephone_line') %>% drop_na())[1]
```

Sobrre un total de `48247` observaciones, lo cual representa el  `43 %` de las observaciones. 


```{r precio,  fig.cap='Histograma del precio de oferta de los apartamentos a la venta en Montevideo (en logaritmos)'}

aptos %>% ggplot(aes(x=log(price))) + 
       geom_histogram(fill = 'darkgreen', alpha = 1, bins = 40) +
      theme(axis.ticks.x = element_blank(),
            legend.position = 'none',
            axis.title.y = element_blank(),
            axis.title.x = element_text(face = 'bold', size = 12),
            axis.text.x = element_text(face = 'bold')) +
      xlim(9,16) +
      labs(x = 'Precio de oferta (en logaritmos)') +
      scale_fill_manual(values = c('darkgreen')) 
     
```


```{r itemconbar, fig.cap='Gráfico de barras de la condición del apartamento'}
aptos %>% ggplot() +
      geom_bar(aes(x = fct_infreq(as.factor(item_condition)), y = (..count..)/sum(..count..), fill = item_condition)) +
      theme(axis.ticks.x = element_blank(),
            legend.position = 'none',
            axis.title.y = element_blank(),
            axis.title.x = element_text(face = 'bold', size = 12),
            axis.text.x = element_text(face = 'bold')) + 
      scale_y_continuous(labels = scales::percent) +
      geom_text(aes(x = as.factor(item_condition),label = scales::percent(round((..count..)/sum(..count..), 2)), 
                    y = (..count..)/sum(..count..)), stat = "count", vjust = -0.5, size = 4) + 
      labs(x = 'Condición del apartamento', fill = 'Condición del apartamento') 

```


```{r itemcondviolin1, fig.cap='Gráfico de Violin del precio de publicación según la condición del item'}

aptos %>% filter(price < quantile(aptos$price, 0.9),
                 price > quantile(aptos$price, 0.1)) %>%
      ggplot(aes(x=as.character(item_condition), y=price, fill=as.character(item_condition))) + 
      geom_violin() +
      theme(text = element_text( family = 'sans'),
            axis.title.y = element_text( size = 14),
            axis.title.x = element_blank(),
            plot.title = element_blank(),
            legend.title = element_blank(),
            axis.text.x = element_text(face = 'bold', size = 12),
            axis.text.y = element_text(face = 'bold', size = 12),
            legend.position = 'none') +
                  scale_x_discrete() +
      ylab('Precio de publicación') +
      geom_boxplot(width=0.1, colour='black', outlier.color = 'black') 
```



```{r itemcondviolin, fig.cap='Gráfico de Violin del precio de publicación según la condición del item'}

aptos %>% 
      ggplot(aes(x=as.character(item_condition), y=log(price), fill=as.character(item_condition))) + 
      geom_violin() +
      theme(text = element_text( family = 'sans'),
            axis.title.y = element_text( size = 14),
            axis.title.x = element_blank(),
            plot.title = element_blank(),
            legend.title = element_blank(),
            axis.text.x = element_text(face = 'bold', size = 12),
            axis.text.y = element_text(face = 'bold', size = 12),
            legend.position = 'none') +
                  scale_x_discrete() +
      ylab('Precio de publicación (en logaritmos)') +
      geom_boxplot(width=0.1, colour='black', outlier.color = 'black') +
      ylim(9,14)
```



```{r itemcond2,  fig.cap='Gráfico de Violin del precio de publicación (en logaritmos) según la condición del item y la cantidad de baños'}

aptos %>% mutate(full_bathrooms = as.numeric(full_bathrooms),
                 banios = ifelse(is.na(full_bathrooms), NA,
                                 ifelse(full_bathrooms == '1', 'Un solo baño', 
                                        'Mas de un baño'))) %>%
      ggplot(aes(x=as.character(item_condition), y=log(price), fill=as.character(item_condition))) + 
      geom_violin() +
      theme(text = element_text( family = 'sans'),
            axis.title.y = element_text( size = 14),
            axis.title.x = element_blank(),
            plot.title = element_blank(),
            legend.title = element_blank(),
            axis.text.x = element_text(face = 'bold', size = 12),
            axis.text.y = element_text(face = 'bold', size = 12),
            legend.position = 'none') +
                  scale_x_discrete() +
      ylab('Precio de publicación (en logaritmos)') +
      geom_boxplot(width=0.1, colour='black', outlier.color = 'black') +
      facet_wrap(~banios, ncol = 3) +
      ylim(8,14)

```



```{r fullbath, fig.cap = 'Gráfico de barras de la cantidad de baños completos'}
aptos %>% ggplot() +
      geom_bar(aes(x = fct_infreq(as.factor(full_bathrooms)), y = (..count..)/sum(..count..), fill = full_bathrooms)) +
      theme(axis.ticks.x = element_blank(),
            legend.position = 'none',
            axis.title.y = element_blank(),
            axis.title.x = element_text(face = 'bold', size = 12),
            axis.text.x = element_text(face = 'bold')) + 
      scale_y_continuous(labels = scales::percent) +
      geom_text(aes(x = as.factor(full_bathrooms),label = scales::percent(round((..count..)/sum(..count..), 2)), 
                    y = (..count..)/sum(..count..)), stat = "count", vjust = -0.5, size = 3) + 
      labs(x = 'Cantidad de baños completos')

```

```{r pricebath, fig.cap='Gráfico de Violin del precio de publicación (en logaritmos) según el apartamento tenga un solo baño (o ninguno) completo o más de uno'}

aptos %>% mutate(full_bathrooms = as.numeric(full_bathrooms),
                 banios = ifelse(is.na(full_bathrooms), NA,
                                 ifelse(full_bathrooms == 1 | full_bathrooms == 0 , 'Un solo baño', 
                                        'Mas de un baño'))) %>%
      filter(!is.na(full_bathrooms)) %>%
      ggplot(aes(x=as.character(banios), y=log(price), fill=as.character(banios))) + 
      geom_violin() +
      theme(text = element_text( family = 'sans'),
            axis.title.y = element_text( size = 14),
            axis.title.x = element_blank(),
            plot.title = element_blank(),
            legend.title = element_blank(),
            axis.text.x = element_text(face = 'bold', size = 12),
            axis.text.y = element_text(face = 'bold', size = 12),
            legend.position = 'none') +
                  scale_x_discrete() +
      ylab('Precio de publicación (en logaritmos)') +
      geom_boxplot(width=0.1, colour='black', outlier.color = 'black')

```

```{r pricebath2, fig.cap='Gráfico de Violin del precio de publicación (en logaritmos) según el apartamento tenga uno o dos baños completoa o más de dos'}

aptos %>% mutate(full_bathrooms = as.numeric(full_bathrooms),
                 banios = ifelse(is.na(full_bathrooms), NA,
                                 ifelse(full_bathrooms < 2, 'Dos o menos de 2 baños completos', 
                                        'Mas de 2 baños completos'))) %>%
      filter(!is.na(full_bathrooms)) %>%
      ggplot(aes(x=as.character(banios), y=log(price), fill=as.character(banios))) + 
      geom_violin() +
      theme(text = element_text( family = 'sans'),
            axis.title.y = element_text( size = 14),
            axis.title.x = element_blank(),
            plot.title = element_blank(),
            legend.title = element_blank(),
            axis.text.x = element_text(face = 'bold', size = 12),
            axis.text.y = element_text(face = 'bold', size = 12),
            legend.position = 'none') +
                  scale_x_discrete() +
      ylab('Precio de publicación (en logaritmos)') +
      geom_boxplot(width=0.1, colour='black', outlier.color = 'black') +
      ylim(8,16)

```



```{r rooms, fig.cap = 'Gráfico de barras de la cantidad de habitaciones'}
aptos %>% ggplot() +
      geom_bar(aes(x = fct_infreq(as.factor(rooms)), y = (..count..)/sum(..count..), fill = rooms)) +
      theme(axis.ticks.x = element_blank(),
            legend.position = 'none',
            axis.title.y = element_blank(),
            axis.title.x = element_text(face = 'bold', size = 12),
            axis.text.x = element_text(face = 'bold')) + 
      scale_y_continuous(labels = scales::percent) +
      geom_text(aes(x = as.factor(rooms),label = scales::percent(round((..count..)/sum(..count..), 2)), 
                    y = (..count..)/sum(..count..)), stat = "count", vjust = -0.5, size = 2) + 
      labs(x = 'Cantidad de habitaciones')
```


```{r pricerooms, fig.cap='Gráfico de Violin del precio de publicación (en logaritmos) según el apartamento tenga dos o menos ambientes, o más de dos'}

aptos %>% mutate(rooms = as.numeric(rooms),
                 rooms_discrete = ifelse(is.na(rooms), NA,
                                 ifelse(rooms <= 3, '3 o menos de 3 ambientes', 
                                        'Mas de 3 ambientes'))) %>%
      filter(!is.na(rooms)) %>%
      ggplot(aes(x=as.character(rooms_discrete), y=log(price), fill=as.character(rooms_discrete))) + 
      geom_violin() +
      theme(text = element_text( family = 'sans'),
            axis.title.y = element_text( size = 14),
            axis.title.x = element_blank(),
            plot.title = element_blank(),
            legend.title = element_blank(),
            axis.text.x = element_text(face = 'bold', size = 12),
            axis.text.y = element_text(face = 'bold', size = 12),
            legend.position = 'none') +
                  scale_x_discrete() +
      ylab('Precio de publicación (en logaritmos)') +
      geom_boxplot(width=0.1, colour='black', outlier.color = 'black') +
      ylim(10,15)

```



```{r bedrooms, fig.cap = 'Gráfico de barras de la cantidad de dormitorios'}
aptos %>% ggplot() +
      geom_bar(aes(x = fct_infreq(as.factor(bedrooms)), y = (..count..)/sum(..count..), fill = bedrooms)) +
      theme(axis.ticks.x = element_blank(),
            legend.position = 'none',
            axis.title.y = element_blank(),
            axis.title.x = element_text(face = 'bold', size = 12),
            axis.text.x = element_text(face = 'bold')) + 
      scale_y_continuous(labels = scales::percent) +
      geom_text(aes(x = as.factor(bedrooms),label = scales::percent(round((..count..)/sum(..count..), 2)), 
                    y = (..count..)/sum(..count..)), stat = "count", vjust = -0.5, size = 2) + 
      labs(x = 'Cantidad de dormitorios')
```

```{r pricebedrooms, fig.cap='Gráfico de Violin del precio de publicación (en logaritmos) según el apartamento tenga 0, 1, o más de 1 dormitorio'}

aptos %>% mutate(bedrooms = as.numeric(bedrooms),
                 bedrooms_discrete = ifelse(is.na(bedrooms), NA,
                                 ifelse(bedrooms == 0, '0 dormitorio',
                                        ifelse(bedrooms == 1, '1 dormitorio', 'Más de 1 dormitorio')))) %>%
      ggplot(aes(x=as.character(bedrooms_discrete), y=log(price), fill=as.character(bedrooms_discrete))) + 
      geom_violin() +
      theme(text = element_text( family = 'sans'),
            axis.title.y = element_text( size = 14),
            axis.title.x = element_blank(),
            plot.title = element_blank(),
            legend.title = element_blank(),
            axis.text.x = element_text(face = 'bold', size = 12),
            axis.text.y = element_text(face = 'bold', size = 12),
            legend.position = 'none') +
                  scale_x_discrete() +
      ylab('Precio de publicación (en logaritmos)') +
      geom_boxplot(width=0.1, colour='black', outlier.color = 'black') +
      ylim(8,15)

```



```{r area, fig.cap='Histograma del área cubierta (en m2). Cómo es de esperar dado que estamos trabajando con información de apartamentos, el área total y área cubierta resulta similar'}

aptos %>% select(covered_area, total_area) %>% 
      pivot_longer(cols = c('covered_area','total_area'), names_to = c('Area')) %>% 
      ggplot() +
      geom_histogram(aes(x = value, fill = Area)) +
      theme(axis.ticks.x = element_blank(),
            legend.position = 'none',
            axis.title.y = element_blank(),
            axis.title.x = element_text(face = 'bold', size = 12),
            axis.text.x = element_text(face = 'bold')) +
      xlim(0,200) +
      labs(x = 'Área (en m2)') +
      scale_fill_manual(values = c('firebrick', 'darkgreen')) +
      facet_wrap(~Area)
```


```{r calidadpic, fig.cap='Gráfico de barras de la calidad de la imágen' }

aptos %>% ggplot() +
      geom_bar(aes(x = fct_infreq(as.factor(tags)), y = (..count..)/sum(..count..), fill = tags)) +
      theme(axis.ticks.x = element_blank(),
            legend.position = 'none',
            axis.title.y = element_blank(),
            axis.title.x = element_text(face = 'bold', size = 12),
            axis.text.x = element_text(face = 'bold')) + 
      scale_y_continuous(labels = scales::percent) +
      geom_text(aes(x = as.factor(tags),label = scales::percent(round((..count..)/sum(..count..), 2)), 
                    y = (..count..)/sum(..count..)), stat = "count", vjust = -0.5, size = 4) + 
      labs(x = 'Calidad de la imágen')

```


```{r preciopic, fig.cap='Gráfico de Violin del precio de publicación (en logaritmos) según la calidad de la imagen'}

aptos %>% ggplot(aes(x=as.character(tags), y=log(price), fill=as.character(tags))) + 
      geom_violin() +
      theme(text = element_text( family = 'sans'),
            axis.title.y = element_text( size = 14),
            axis.title.x = element_blank(),
            plot.title = element_blank(),
            legend.title = element_blank(),
            axis.text.x = element_text(face = 'bold', size = 12),
            axis.text.y = element_text(face = 'bold', size = 12),
            legend.position = 'none')  +
      ylab('Precio de publicación (en logaritmos)') +
      geom_boxplot(width=0.1, colour='black', outlier.color = 'black') +
      scale_fill_manual(values = c('navyblue', 'darkgreen', 'firebrick', 'gray')) # no reconoce color

```


```{r aircond, fig.cap = 'Tiene aire acondicionado'}
aptos %>% ggplot() +
      geom_bar(aes(x = fct_infreq(as.factor(has_air_conditioning)), y = (..count..)/sum(..count..), fill = has_air_conditioning)) +
      theme(axis.ticks.x = element_blank(),
            legend.position = 'none',
            axis.title.y = element_blank(),
            axis.title.x = element_text(face = 'bold', size = 12),
            axis.text.x = element_text(face = 'bold')) + 
      scale_y_continuous(labels = scales::percent) +
      geom_text(aes(x = as.factor(has_air_conditioning),label = scales::percent(round((..count..)/sum(..count..), 2)), 
                    y = (..count..)/sum(..count..)), stat = "count", vjust = -0.5, size = 4) + 
      labs(x = 'Tiene aire acondicionado')
```


```{r preciopic, fig.cap='Gráfico de Violin del precio de publicación (en logaritmos) según tiene aire acondicionado'}

aptos %>% ggplot(aes(x=as.character(has_air_conditioning), y=log(price), fill=as.character(has_air_conditioning))) + 
      geom_violin() +
      theme(text = element_text( family = 'sans'),
            axis.title.y = element_text( size = 14),
            axis.title.x = element_blank(),
            plot.title = element_blank(),
            legend.title = element_blank(),
            axis.text.x = element_text(face = 'bold', size = 12),
            axis.text.y = element_text(face = 'bold', size = 12),
            legend.position = 'none')  +
      ylab('Precio de publicación (en logaritmos)') +
      geom_boxplot(width=0.1, colour='black', outlier.color = 'black') +
      scale_fill_manual(values = c('navyblue', 'darkgreen', 'firebrick', 'gray')) # no reconoce color

```



```{r line, fig.cap = 'Tiene línea telefónica'}
aptos %>% ggplot() +
      geom_bar(aes(x = fct_infreq(as.factor(has_telephone_line)), y = (..count..)/sum(..count..), fill = has_telephone_line)) +
      theme(axis.ticks.x = element_blank(),
            legend.position = 'none',
            axis.title.y = element_blank(),
            axis.title.x = element_text(face = 'bold', size = 12),
            axis.text.x = element_text(face = 'bold')) + 
      scale_y_continuous(labels = scales::percent) +
      geom_text(aes(x = as.factor(has_telephone_line),label = scales::percent(round((..count..)/sum(..count..), 2)), 
                    y = (..count..)/sum(..count..)), stat = "count", vjust = -0.5, size = 4) + 
      labs(x = 'Tiene línea telefónica')
```


\newpage

```{r, results='asis'}
kable(aptos %>% filter(state_name == 'Montevideo') %>%
      group_by(city_name) %>% summarise(conteo = n()) %>%
      mutate(prop = conteo/sum(conteo)*100) %>%
      arrange(desc(prop)) %>% filter(prop > 2)) 

```

















